# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body115(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'team': 'int',
        'creator': 'int',
        'imagesets': 'list[int]',
        'annotationtype_set': 'list[int]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'team': 'team',
        'creator': 'creator',
        'imagesets': 'imagesets',
        'annotationtype_set': 'annotationtype_set'
    }

    def __init__(self, name=None, description=None, team=None, creator=None, imagesets=None, annotationtype_set=None):  # noqa: E501
        """Body115 - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._team = None
        self._creator = None
        self._imagesets = None
        self._annotationtype_set = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if team is not None:
            self.team = team
        if creator is not None:
            self.creator = creator
        if imagesets is not None:
            self.imagesets = imagesets
        if annotationtype_set is not None:
            self.annotationtype_set = annotationtype_set

    @property
    def name(self):
        """Gets the name of this Body115.  # noqa: E501


        :return: The name of this Body115.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body115.


        :param name: The name of this Body115.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Body115.  # noqa: E501


        :return: The description of this Body115.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Body115.


        :param description: The description of this Body115.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def team(self):
        """Gets the team of this Body115.  # noqa: E501


        :return: The team of this Body115.  # noqa: E501
        :rtype: int
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this Body115.


        :param team: The team of this Body115.  # noqa: E501
        :type: int
        """

        self._team = team

    @property
    def creator(self):
        """Gets the creator of this Body115.  # noqa: E501


        :return: The creator of this Body115.  # noqa: E501
        :rtype: int
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this Body115.


        :param creator: The creator of this Body115.  # noqa: E501
        :type: int
        """

        self._creator = creator

    @property
    def imagesets(self):
        """Gets the imagesets of this Body115.  # noqa: E501


        :return: The imagesets of this Body115.  # noqa: E501
        :rtype: list[int]
        """
        return self._imagesets

    @imagesets.setter
    def imagesets(self, imagesets):
        """Sets the imagesets of this Body115.


        :param imagesets: The imagesets of this Body115.  # noqa: E501
        :type: list[int]
        """

        self._imagesets = imagesets

    @property
    def annotationtype_set(self):
        """Gets the annotationtype_set of this Body115.  # noqa: E501


        :return: The annotationtype_set of this Body115.  # noqa: E501
        :rtype: list[int]
        """
        return self._annotationtype_set

    @annotationtype_set.setter
    def annotationtype_set(self, annotationtype_set):
        """Sets the annotationtype_set of this Body115.


        :param annotationtype_set: The annotationtype_set of this Body115.  # noqa: E501
        :type: list[int]
        """

        self._annotationtype_set = annotationtype_set

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body115, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body115):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
