# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LogImageAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'image': 'int',
        'user': 'int',
        'time': 'datetime',
        'action': 'int',
        'ip': 'str'
    }

    attribute_map = {
        'id': 'id',
        'image': 'image',
        'user': 'user',
        'time': 'time',
        'action': 'action',
        'ip': 'ip'
    }

    def __init__(self, id=None, image=None, user=None, time=None, action=None, ip=None):  # noqa: E501
        """LogImageAction - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._image = None
        self._user = None
        self._time = None
        self._action = None
        self._ip = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if user is not None:
            self.user = user
        if time is not None:
            self.time = time
        if action is not None:
            self.action = action
        if ip is not None:
            self.ip = ip

    @property
    def id(self):
        """Gets the id of this LogImageAction.  # noqa: E501


        :return: The id of this LogImageAction.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LogImageAction.


        :param id: The id of this LogImageAction.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this LogImageAction.  # noqa: E501


        :return: The image of this LogImageAction.  # noqa: E501
        :rtype: int
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this LogImageAction.


        :param image: The image of this LogImageAction.  # noqa: E501
        :type: int
        """

        self._image = image

    @property
    def user(self):
        """Gets the user of this LogImageAction.  # noqa: E501


        :return: The user of this LogImageAction.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this LogImageAction.


        :param user: The user of this LogImageAction.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def time(self):
        """Gets the time of this LogImageAction.  # noqa: E501


        :return: The time of this LogImageAction.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this LogImageAction.


        :param time: The time of this LogImageAction.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def action(self):
        """Gets the action of this LogImageAction.  # noqa: E501


        :return: The action of this LogImageAction.  # noqa: E501
        :rtype: int
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this LogImageAction.


        :param action: The action of this LogImageAction.  # noqa: E501
        :type: int
        """

        self._action = action

    @property
    def ip(self):
        """Gets the ip of this LogImageAction.  # noqa: E501


        :return: The ip of this LogImageAction.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this LogImageAction.


        :param ip: The ip of this LogImageAction.  # noqa: E501
        :type: str
        """

        self._ip = ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LogImageAction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogImageAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
