# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PluginJob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'creator': 'int',
        'plugin': 'int',
        'image' : 'int',
        'created_time': 'datetime',
        'eta_time': 'datetime',
        'processing_complete': 'float',
        'updated_time': 'datetime',
        'result': 'int'
    }

    attribute_map = {
        'id': 'id',
        'creator': 'creator',
        'plugin': 'plugin',
        'image': 'image',
        'created_time': 'created_time',
        'eta_time': 'eta_time',
        'processing_complete': 'processing_complete',
        'updated_time': 'updated_time',
        'result': 'result'
    }

    def __init__(self, id=None, creator=None, plugin=None, image=None, created_time=None, eta_time=None, processing_complete=None, updated_time=None, result=None):  # noqa: E501
        """PluginJob - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._creator = None
        self._plugin = None
        self._image = None
        self._created_time = None
        self._eta_time = None
        self._processing_complete = None
        self._updated_time = None
        self._result = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if creator is not None:
            self.creator = creator
        self.plugin = plugin
        if created_time is not None:
            self.created_time = created_time
        if eta_time is not None:
            self.eta_time = eta_time
        if processing_complete is not None:
            self.processing_complete = processing_complete
        if updated_time is not None:
            self.updated_time = updated_time
        self.result = result

    @property
    def id(self):
        """Gets the id of this PluginJob.  # noqa: E501


        :return: The id of this PluginJob.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PluginJob.


        :param id: The id of this PluginJob.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this PluginJob.  # noqa: E501


        :return: The image of this PluginJob.  # noqa: E501
        :rtype: int
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this PluginJob.


        :param image: The image of this PluginJob.  # noqa: E501
        :type: int
        """

        self._image = image

    @property
    def creator(self):
        """Gets the creator of this PluginJob.  # noqa: E501


        :return: The creator of this PluginJob.  # noqa: E501
        :rtype: int
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this PluginJob.


        :param creator: The creator of this PluginJob.  # noqa: E501
        :type: int
        """

        self._creator = creator

    @property
    def plugin(self):
        """Gets the plugin of this PluginJob.  # noqa: E501


        :return: The plugin of this PluginJob.  # noqa: E501
        :rtype: int
        """
        return self._plugin

    @plugin.setter
    def plugin(self, plugin):
        """Sets the plugin of this PluginJob.


        :param plugin: The plugin of this PluginJob.  # noqa: E501
        :type: int
        """
        if plugin is None:
            raise ValueError("Invalid value for `plugin`, must not be `None`")  # noqa: E501

        self._plugin = plugin

    @property
    def created_time(self):
        """Gets the created_time of this PluginJob.  # noqa: E501


        :return: The created_time of this PluginJob.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this PluginJob.


        :param created_time: The created_time of this PluginJob.  # noqa: E501
        :type: datetime
        """

        self._created_time = created_time

    @property
    def eta_time(self):
        """Gets the eta_time of this PluginJob.  # noqa: E501


        :return: The eta_time of this PluginJob.  # noqa: E501
        :rtype: datetime
        """
        return self._eta_time

    @eta_time.setter
    def eta_time(self, eta_time):
        """Sets the eta_time of this PluginJob.


        :param eta_time: The eta_time of this PluginJob.  # noqa: E501
        :type: datetime
        """

        self._eta_time = eta_time

    @property
    def processing_complete(self):
        """Gets the processing_complete of this PluginJob.  # noqa: E501


        :return: The processing_complete of this PluginJob.  # noqa: E501
        :rtype: float
        """
        return self._processing_complete

    @processing_complete.setter
    def processing_complete(self, processing_complete):
        """Sets the processing_complete of this PluginJob.


        :param processing_complete: The processing_complete of this PluginJob.  # noqa: E501
        :type: float
        """

        self._processing_complete = processing_complete

    @property
    def updated_time(self):
        """Gets the updated_time of this PluginJob.  # noqa: E501


        :return: The updated_time of this PluginJob.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_time

    @updated_time.setter
    def updated_time(self, updated_time):
        """Sets the updated_time of this PluginJob.


        :param updated_time: The updated_time of this PluginJob.  # noqa: E501
        :type: datetime
        """

        self._updated_time = updated_time

    @property
    def result(self):
        """Gets the result of this PluginJob.  # noqa: E501


        :return: The result of this PluginJob.  # noqa: E501
        :rtype: int
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this PluginJob.


        :param result: The result of this PluginJob.  # noqa: E501
        :type: int
        """

        self._result = result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PluginJob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PluginJob):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
