# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TeamMembership(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'is_admin': 'bool',
        'team': 'int',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'is_admin': 'is_admin',
        'team': 'team',
        'user': 'user'
    }

    def __init__(self, id=None, is_admin=None, team=None, user=None):  # noqa: E501
        """TeamMembership - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_admin = None
        self._team = None
        self._user = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if is_admin is not None:
            self.is_admin = is_admin
        self.team = team
        self.user = user

    @property
    def id(self):
        """Gets the id of this TeamMembership.  # noqa: E501


        :return: The id of this TeamMembership.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TeamMembership.


        :param id: The id of this TeamMembership.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def is_admin(self):
        """Gets the is_admin of this TeamMembership.  # noqa: E501


        :return: The is_admin of this TeamMembership.  # noqa: E501
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin):
        """Sets the is_admin of this TeamMembership.


        :param is_admin: The is_admin of this TeamMembership.  # noqa: E501
        :type: bool
        """

        self._is_admin = is_admin

    @property
    def team(self):
        """Gets the team of this TeamMembership.  # noqa: E501


        :return: The team of this TeamMembership.  # noqa: E501
        :rtype: int
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this TeamMembership.


        :param team: The team of this TeamMembership.  # noqa: E501
        :type: int
        """
        if team is None:
            raise ValueError("Invalid value for `team`, must not be `None`")  # noqa: E501

        self._team = team

    @property
    def user(self):
        """Gets the user of this TeamMembership.  # noqa: E501


        :return: The user of this TeamMembership.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this TeamMembership.


        :param user: The user of this TeamMembership.  # noqa: E501
        :type: int
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TeamMembership, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamMembership):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
