# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import
from exact_sync.v1.api.pagination_base_api import PaginationBaseAPI
import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from exact_sync.v1.api_client import ApiClient


class ScreeningModesApi(PaginationBaseAPI):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_screening_mode(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body54 body:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_screening_mode_with_http_info(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body54 body:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_screening_mode(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_screening_mode_with_http_info(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_screening_mode(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_screening_mode_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_screening_mode_with_http_info(self, **kwargs):  # noqa: E501
        """create_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_screening_mode_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def destroy_screening_mode(self, id, **kwargs):  # noqa: E501
        """destroy_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str image: image
        :param str user: user
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.destroy_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.destroy_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def destroy_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """destroy_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str image: image
        :param str user: user
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'id2', 'image', 'user']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method destroy_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `destroy_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image' in params:
            query_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_screening_modes(self, pagination:bool=True, **kwargs):  # noqa: E501
        """list_screening_modes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_screening_modes(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :param str id: id
        :param str image: image
        :param str user: user
        :return: ScreeningModes
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if pagination:
            if kwargs.get('async_req'):
                return self.list_screening_modes_with_http_info(**kwargs)  # noqa: E501
            else:
                (data) = self.list_screening_modes_with_http_info(**kwargs)  # noqa: E501
                return data
        else:
            return self._get_all(self.list_screening_modes_with_http_info, **kwargs)

    def list_screening_modes_with_http_info(self, **kwargs):  # noqa: E501
        """list_screening_modes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_screening_modes_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :param str id: id
        :param str image: image
        :param str user: user
        :return: ScreeningModes
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['limit', 'offset', 'id', 'image', 'user']  # noqa: E501
        all_params.append('omit')
        all_params.append('fields')
        all_params.append('expand')     
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_screening_modes" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'image' in params:
            query_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'omit' in params:
            query_params.append(('omit', params['omit']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E501
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningModes',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_screening_mode(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body60 body:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body60 body:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'body', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_screening_mode(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_screening_mode(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_screening_mode(self, id, **kwargs):  # noqa: E501
        """retrieve_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str image: image
        :param str user: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def retrieve_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """retrieve_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str image: image
        :param str user: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'id2', 'image', 'user']  # noqa: E501
        all_params.append('omit')
        all_params.append('fields')
        all_params.append('expand')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `retrieve_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image' in params:
            query_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'omit' in params:
            query_params.append(('omit', params['omit']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E50
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
            
        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_screening_mode(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body57 body:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body57 body:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'body', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_screening_mode(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_screening_mode(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_screening_mode_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_screening_mode_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_screening_mode  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_screening_mode_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int image:
        :param int user:
        :param object screening_tiles:
        :param int x_steps:
        :param int y_steps:
        :param int x_resolution:
        :param int y_resolution:
        :param int current_index:
        :param str id2: id
        :param str image2: image
        :param str user2: user
        :return: ScreeningMode
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'image', 'user', 'screening_tiles', 'x_steps', 'y_steps', 'x_resolution', 'y_resolution', 'current_index', 'id2', 'image2', 'user2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_screening_mode" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_screening_mode`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'image2' in params:
            query_params.append(('image', params['image2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501
        if 'image' in params:
            form_params.append(('image', params['image']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'screening_tiles' in params:
            form_params.append(('screening_tiles', params['screening_tiles']))  # noqa: E501
        if 'x_steps' in params:
            form_params.append(('x_steps', params['x_steps']))  # noqa: E501
        if 'y_steps' in params:
            form_params.append(('y_steps', params['y_steps']))  # noqa: E501
        if 'x_resolution' in params:
            form_params.append(('x_resolution', params['x_resolution']))  # noqa: E501
        if 'y_resolution' in params:
            form_params.append(('y_resolution', params['y_resolution']))  # noqa: E501
        if 'current_index' in params:
            form_params.append(('current_index', params['current_index']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/images/screening_modes/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ScreeningMode',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
