# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import
from exact_sync.v1.api.pagination_base_api import PaginationBaseAPI
import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from exact_sync.v1.api_client import ApiClient


class VerificationsApi(PaginationBaseAPI):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_verification(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body90 body:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_verification_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_verification_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_verification_with_http_info(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Body90 body:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_verification" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_verification(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int annotation:
        :param int user:
        :param bool verified:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_verification_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_verification_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_verification_with_http_info(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int annotation:
        :param int user:
        :param bool verified:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['annotation', 'user', 'verified']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_verification" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_verification(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int annotation:
        :param int user:
        :param bool verified:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_verification_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_verification_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_verification_with_http_info(self, **kwargs):  # noqa: E501
        """create_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_verification_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int annotation:
        :param int user:
        :param bool verified:
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['annotation', 'user', 'verified']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_verification" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def destroy_verification(self, id, **kwargs):  # noqa: E501
        """destroy_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.destroy_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.destroy_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def destroy_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """destroy_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.destroy_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'id2', 'annotation', 'user', 'time', 'time__lte', 'time__gte', 'time__range', 'verified']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method destroy_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `destroy_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation' in params:
            query_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified' in params:
            query_params.append(('verified', params['verified']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_verifications(self, pagination:bool=True, **kwargs):  # noqa: E501
        """list_verifications  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_verifications(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :param str id: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: Verifications
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if pagination:
            if kwargs.get('async_req'):
                return self.list_verifications_with_http_info(**kwargs)  # noqa: E501
            else:
                (data) = self.list_verifications_with_http_info(**kwargs)  # noqa: E501
                return data
        else:
            return self._get_all(self.list_verifications_with_http_info, **kwargs)

    def list_verifications_with_http_info(self, **kwargs):  # noqa: E501
        """list_verifications  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_verifications_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :param str id: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: Verifications
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['limit', 'offset', 'id', 'annotation', 'user', 'time', 'time__lte', 'time__gte', 'time__range', 'verified']  # noqa: E501
        all_params.append('omit')
        all_params.append('fields')
        all_params.append('expand')      
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_verifications" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'annotation' in params:
            query_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified' in params:
            query_params.append(('verified', params['verified']))  # noqa: E501
        if 'omit' in params:
            query_params.append(('omit', params['omit']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E50
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
            
        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verifications',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_verification(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body96 body:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body96 body:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'body', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_verification(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'annotation', 'user', 'verified', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def partial_update_verification(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.partial_update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def partial_update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """partial_update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.partial_update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'annotation', 'user', 'verified', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method partial_update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `partial_update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_verification(self, id, **kwargs):  # noqa: E501
        """retrieve_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.retrieve_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def retrieve_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """retrieve_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.retrieve_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param str id2: id
        :param str annotation: annotation
        :param str user: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'id2', 'annotation', 'user', 'time', 'time__lte', 'time__gte', 'time__range', 'verified']  # noqa: E501
        all_params.append('async_req')
        all_params.append('omit')
        all_params.append('fields')
        all_params.append('expand')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `retrieve_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation' in params:
            query_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified' in params:
            query_params.append(('verified', params['verified']))  # noqa: E501
        if 'omit' in params:
            query_params.append(('omit', params['omit']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E50
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
            
        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_verification(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body93 body:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param Body93 body:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'body', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_verification(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'annotation', 'user', 'verified', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_verification(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_verification_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def update_verification_with_http_info(self, id, **kwargs):  # noqa: E501
        """update_verification  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_verification_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param int annotation:
        :param int user:
        :param bool verified:
        :param str id2: id
        :param str annotation2: annotation
        :param str user2: user
        :param str time: time
        :param str time__lte: time__lte
        :param str time__gte: time__gte
        :param str time__range: time__range
        :param str verified2: verified
        :return: Verification
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'annotation', 'user', 'verified', 'id2', 'annotation2', 'user2', 'time', 'time__lte', 'time__gte', 'time__range', 'verified2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_verification" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `update_verification`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'id2' in params:
            query_params.append(('id', params['id2']))  # noqa: E501
        if 'annotation2' in params:
            query_params.append(('annotation', params['annotation2']))  # noqa: E501
        if 'user2' in params:
            query_params.append(('user', params['user2']))  # noqa: E501
        if 'time' in params:
            query_params.append(('time', params['time']))  # noqa: E501
        if 'time__lte' in params:
            query_params.append(('time__lte', params['time__lte']))  # noqa: E501
        if 'time__gte' in params:
            query_params.append(('time__gte', params['time__gte']))  # noqa: E501
        if 'time__range' in params:
            query_params.append(('time__range', params['time__range']))  # noqa: E501
        if 'verified2' in params:
            query_params.append(('verified', params['verified2']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501
        if 'annotation' in params:
            form_params.append(('annotation', params['annotation']))  # noqa: E501
        if 'user' in params:
            form_params.append(('user', params['user']))  # noqa: E501
        if 'verified' in params:
            form_params.append(('verified', params['verified']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/annotations/verifications/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Verification',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
