# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_product(self):
        """Test case for create_product

        """
        pass

    def test_destroy_product(self):
        """Test case for destroy_product

        """
        pass

    def test_list_products(self):
        """Test case for list_products

        """
        pass

    def test_partial_update_product(self):
        """Test case for partial_update_product

        """
        pass

    def test_retrieve_product(self):
        """Test case for retrieve_product

        """
        pass

    def test_update_product(self):
        """Test case for update_product

        """
        pass


if __name__ == '__main__':
    unittest.main()
