# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from exact_sync.v1.api_client import ApiClient as client
from exact_sync.v1.api.screening_modes_api import ScreeningModesApi  # noqa: E501
from exact_sync.v1.rest import ApiException


class TestScreeningModesApi(unittest.TestCase):
    """ScreeningModesApi unit test stubs"""

    def setUp(self):
        self.api = ScreeningModesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_screening_mode(self):
        """Test case for create_screening_mode

        """
        assert False

    def test_destroy_screening_mode(self):
        """Test case for destroy_screening_mode

        """
        assert False

    def test_list_screening_modes(self):
        """Test case for list_screening_modes

        """
        screening_modes = self.api.list_screening_modes()
        pass

    def test_partial_update_screening_mode(self):
        """Test case for partial_update_screening_mode

        """
        assert False

    def test_retrieve_screening_mode(self):
        """Test case for retrieve_screening_mode

        """
        screening_modes = self.api.list_screening_modes()
        screening_mode = screening_modes.results[0]
        screening_mode = self.api.retrieve_screening_mode(id=screening_mode.id)

        pass

    def test_update_screening_mode(self):
        """Test case for update_screening_mode

        """
        assert False


if __name__ == '__main__':
    unittest.main()
