# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.verifications_api import VerificationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVerificationsApi(unittest.TestCase):
    """VerificationsApi unit test stubs"""

    def setUp(self):
        self.api = api.verifications_api.VerificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_verification(self):
        """Test case for create_verification

        """
        pass

    def test_destroy_verification(self):
        """Test case for destroy_verification

        """
        pass

    def test_list_verifications(self):
        """Test case for list_verifications

        """
        pass

    def test_partial_update_verification(self):
        """Test case for partial_update_verification

        """
        pass

    def test_retrieve_verification(self):
        """Test case for retrieve_verification

        """
        pass

    def test_update_verification(self):
        """Test case for update_verification

        """
        pass


if __name__ == '__main__':
    unittest.main()
