# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.annotations_api import AnnotationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = api.annotations_api.AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_annotation(self):
        """Test case for create_annotation

        """
        pass

    def test_destroy_annotation(self):
        """Test case for destroy_annotation

        """
        pass

    def test_list_annotations(self):
        """Test case for list_annotations

        """
        pass

    def test_partial_update_annotation(self):
        """Test case for partial_update_annotation

        """
        pass

    def test_retrieve_annotation(self):
        """Test case for retrieve_annotation

        """
        pass

    def test_update_annotation(self):
        """Test case for update_annotation

        """
        pass


if __name__ == '__main__':
    unittest.main()
