# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.team_membership_api import TeamMembershipApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamMembershipApi(unittest.TestCase):
    """TeamMembershipApi unit test stubs"""

    def setUp(self):
        self.api = api.team_membership_api.TeamMembershipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_team_membership(self):
        """Test case for create_team_membership

        """
        pass

    def test_destroy_team_membership(self):
        """Test case for destroy_team_membership

        """
        pass

    def test_list_team_memberships(self):
        """Test case for list_team_memberships

        """
        pass

    def test_partial_update_team_membership(self):
        """Test case for partial_update_team_membership

        """
        pass

    def test_retrieve_team_membership(self):
        """Test case for retrieve_team_membership

        """
        pass

    def test_update_team_membership(self):
        """Test case for update_team_membership

        """
        pass


if __name__ == '__main__':
    unittest.main()
