# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.set_tags_api import SetTagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSetTagsApi(unittest.TestCase):
    """SetTagsApi unit test stubs"""

    def setUp(self):
        self.api = api.set_tags_api.SetTagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_set_tag(self):
        """Test case for create_set_tag

        """
        pass

    def test_destroy_set_tag(self):
        """Test case for destroy_set_tag

        """
        pass

    def test_list_set_tags(self):
        """Test case for list_set_tags

        """
        pass

    def test_partial_update_set_tag(self):
        """Test case for partial_update_set_tag

        """
        pass

    def test_retrieve_set_tag(self):
        """Test case for retrieve_set_tag

        """
        pass

    def test_update_set_tag(self):
        """Test case for update_set_tag

        """
        pass


if __name__ == '__main__':
    unittest.main()
