# coding: utf-8

"""
    EXACT - API

    API to interact with the EXACT Server  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from exact_sync.v1.api_client import ApiClient as client
from exact_sync.v1.api.annotation_types_api import AnnotationTypesApi  # noqa: E501
from exact_sync.v1.rest import ApiException


class TestAnnotationTypesApi(unittest.TestCase):
    """AnnotationTypesApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_annotation_type(self):
        """Test case for create_annotation_type

        """
        pass

    def test_destroy_annotation_type(self):
        """Test case for destroy_annotation_type

        """
        pass

    def test_list_annotation_types(self):
        """Test case for list_annotation_types

        """
        annotation_type_list = self.api.list_annotation_types()

        pass

    def test_partial_update_annotation_type(self):
        """Test case for partial_update_annotation_type

        """
        pass

    def test_retrieve_annotation_type(self):
        """Test case for retrieve_annotation_type

        """
        annotation_type_list = self.api.list_annotation_types()
        annotation_type = annotation_type_list.results[0]
        annotation_type = self.api.retrieve_annotation_type(id=annotation_type.id)
        pass

    def test_update_annotation_type(self):
        """Test case for update_annotation_type

        """
        pass


if __name__ == '__main__':
    unittest.main()
